/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package vpngateway

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"

	svcapitypes "github.com/crossplane/provider-aws/apis/ec2/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeVpnGatewaysInput returns input for read
// operation.
func GenerateDescribeVpnGatewaysInput(cr *svcapitypes.VPNGateway) *svcsdk.DescribeVpnGatewaysInput {
	res := &svcsdk.DescribeVpnGatewaysInput{}

	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Status.AtProvider.VPNGatewayID != nil {
		f2 := []*string{}
		f2 = append(f2, cr.Status.AtProvider.VPNGatewayID)
		res.SetVpnGatewayIds(f2)
	}

	return res
}

// GenerateVPNGateway returns the current state in the form of *svcapitypes.VPNGateway.
func GenerateVPNGateway(resp *svcsdk.DescribeVpnGatewaysOutput) *svcapitypes.VPNGateway {
	cr := &svcapitypes.VPNGateway{}

	found := false
	for _, elem := range resp.VpnGateways {
		if elem.AmazonSideAsn != nil {
			cr.Spec.ForProvider.AmazonSideASN = elem.AmazonSideAsn
		} else {
			cr.Spec.ForProvider.AmazonSideASN = nil
		}
		if elem.AvailabilityZone != nil {
			cr.Spec.ForProvider.AvailabilityZone = elem.AvailabilityZone
		} else {
			cr.Spec.ForProvider.AvailabilityZone = nil
		}
		if elem.State != nil {
			cr.Status.AtProvider.State = elem.State
		} else {
			cr.Status.AtProvider.State = nil
		}
		if elem.Tags != nil {
			f3 := []*svcapitypes.Tag{}
			for _, f3iter := range elem.Tags {
				f3elem := &svcapitypes.Tag{}
				if f3iter.Key != nil {
					f3elem.Key = f3iter.Key
				}
				if f3iter.Value != nil {
					f3elem.Value = f3iter.Value
				}
				f3 = append(f3, f3elem)
			}
			cr.Status.AtProvider.Tags = f3
		} else {
			cr.Status.AtProvider.Tags = nil
		}
		if elem.Type != nil {
			cr.Spec.ForProvider.Type = elem.Type
		} else {
			cr.Spec.ForProvider.Type = nil
		}
		if elem.VpcAttachments != nil {
			f5 := []*svcapitypes.VPCAttachment{}
			for _, f5iter := range elem.VpcAttachments {
				f5elem := &svcapitypes.VPCAttachment{}
				if f5iter.State != nil {
					f5elem.State = f5iter.State
				}
				if f5iter.VpcId != nil {
					f5elem.VPCID = f5iter.VpcId
				}
				f5 = append(f5, f5elem)
			}
			cr.Status.AtProvider.VPCAttachments = f5
		} else {
			cr.Status.AtProvider.VPCAttachments = nil
		}
		if elem.VpnGatewayId != nil {
			cr.Status.AtProvider.VPNGatewayID = elem.VpnGatewayId
		} else {
			cr.Status.AtProvider.VPNGatewayID = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateVpnGatewayInput returns a create input.
func GenerateCreateVpnGatewayInput(cr *svcapitypes.VPNGateway) *svcsdk.CreateVpnGatewayInput {
	res := &svcsdk.CreateVpnGatewayInput{}

	if cr.Spec.ForProvider.AmazonSideASN != nil {
		res.SetAmazonSideAsn(*cr.Spec.ForProvider.AmazonSideASN)
	}
	if cr.Spec.ForProvider.AvailabilityZone != nil {
		res.SetAvailabilityZone(*cr.Spec.ForProvider.AvailabilityZone)
	}
	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Spec.ForProvider.TagSpecifications != nil {
		f3 := []*svcsdk.TagSpecification{}
		for _, f3iter := range cr.Spec.ForProvider.TagSpecifications {
			f3elem := &svcsdk.TagSpecification{}
			if f3iter.ResourceType != nil {
				f3elem.SetResourceType(*f3iter.ResourceType)
			}
			if f3iter.Tags != nil {
				f3elemf1 := []*svcsdk.Tag{}
				for _, f3elemf1iter := range f3iter.Tags {
					f3elemf1elem := &svcsdk.Tag{}
					if f3elemf1iter.Key != nil {
						f3elemf1elem.SetKey(*f3elemf1iter.Key)
					}
					if f3elemf1iter.Value != nil {
						f3elemf1elem.SetValue(*f3elemf1iter.Value)
					}
					f3elemf1 = append(f3elemf1, f3elemf1elem)
				}
				f3elem.SetTags(f3elemf1)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTagSpecifications(f3)
	}
	if cr.Spec.ForProvider.Type != nil {
		res.SetType(*cr.Spec.ForProvider.Type)
	}

	return res
}

// GenerateDeleteVpnGatewayInput returns a deletion input.
func GenerateDeleteVpnGatewayInput(cr *svcapitypes.VPNGateway) *svcsdk.DeleteVpnGatewayInput {
	res := &svcsdk.DeleteVpnGatewayInput{}

	if cr.Spec.ForProvider.DryRun != nil {
		res.SetDryRun(*cr.Spec.ForProvider.DryRun)
	}
	if cr.Status.AtProvider.VPNGatewayID != nil {
		res.SetVpnGatewayId(*cr.Status.AtProvider.VPNGatewayID)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
