/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package vpngateway

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/ec2"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	svcsdkapi "github.com/aws/aws-sdk-go/service/ec2/ec2iface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/ec2/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an VPNGateway resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create VPNGateway in AWS"
	errUpdate        = "cannot update VPNGateway in AWS"
	errDescribe      = "failed to describe VPNGateway"
	errDelete        = "failed to delete VPNGateway"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.VPNGateway)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.VPNGateway)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeVpnGatewaysInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeVpnGatewaysWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	resp = e.filterList(cr, resp)
	if len(resp.VpnGateways) == 0 {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateVPNGateway(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.VPNGateway)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateVpnGatewayInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateVpnGatewayWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.VpnGateway.AmazonSideAsn != nil {
		cr.Spec.ForProvider.AmazonSideASN = resp.VpnGateway.AmazonSideAsn
	} else {
		cr.Spec.ForProvider.AmazonSideASN = nil
	}
	if resp.VpnGateway.AvailabilityZone != nil {
		cr.Spec.ForProvider.AvailabilityZone = resp.VpnGateway.AvailabilityZone
	} else {
		cr.Spec.ForProvider.AvailabilityZone = nil
	}
	if resp.VpnGateway.State != nil {
		cr.Status.AtProvider.State = resp.VpnGateway.State
	} else {
		cr.Status.AtProvider.State = nil
	}
	if resp.VpnGateway.Tags != nil {
		f3 := []*svcapitypes.Tag{}
		for _, f3iter := range resp.VpnGateway.Tags {
			f3elem := &svcapitypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, f3elem)
		}
		cr.Status.AtProvider.Tags = f3
	} else {
		cr.Status.AtProvider.Tags = nil
	}
	if resp.VpnGateway.Type != nil {
		cr.Spec.ForProvider.Type = resp.VpnGateway.Type
	} else {
		cr.Spec.ForProvider.Type = nil
	}
	if resp.VpnGateway.VpcAttachments != nil {
		f5 := []*svcapitypes.VPCAttachment{}
		for _, f5iter := range resp.VpnGateway.VpcAttachments {
			f5elem := &svcapitypes.VPCAttachment{}
			if f5iter.State != nil {
				f5elem.State = f5iter.State
			}
			if f5iter.VpcId != nil {
				f5elem.VPCID = f5iter.VpcId
			}
			f5 = append(f5, f5elem)
		}
		cr.Status.AtProvider.VPCAttachments = f5
	} else {
		cr.Status.AtProvider.VPCAttachments = nil
	}
	if resp.VpnGateway.VpnGatewayId != nil {
		cr.Status.AtProvider.VPNGatewayID = resp.VpnGateway.VpnGatewayId
	} else {
		cr.Status.AtProvider.VPNGatewayID = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	return e.update(ctx, mg)

}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.VPNGateway)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteVpnGatewayInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteVpnGatewayWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.EC2API, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		filterList:     nopFilterList,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.EC2API
	preObserve     func(context.Context, *svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysInput) error
	postObserve    func(context.Context, *svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	filterList     func(*svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysOutput) *svcsdk.DescribeVpnGatewaysOutput
	lateInitialize func(*svcapitypes.VPNGatewayParameters, *svcsdk.DescribeVpnGatewaysOutput) error
	isUpToDate     func(*svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.VPNGateway, *svcsdk.CreateVpnGatewayInput) error
	postCreate     func(context.Context, *svcapitypes.VPNGateway, *svcsdk.CreateVpnGatewayOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.VPNGateway, *svcsdk.DeleteVpnGatewayInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.VPNGateway, *svcsdk.DeleteVpnGatewayOutput, error) error
	update         func(context.Context, cpresource.Managed) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysInput) error {
	return nil
}
func nopPostObserve(_ context.Context, _ *svcapitypes.VPNGateway, _ *svcsdk.DescribeVpnGatewaysOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopFilterList(_ *svcapitypes.VPNGateway, list *svcsdk.DescribeVpnGatewaysOutput) *svcsdk.DescribeVpnGatewaysOutput {
	return list
}

func nopLateInitialize(*svcapitypes.VPNGatewayParameters, *svcsdk.DescribeVpnGatewaysOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.VPNGateway, *svcsdk.DescribeVpnGatewaysOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.VPNGateway, *svcsdk.CreateVpnGatewayInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.VPNGateway, _ *svcsdk.CreateVpnGatewayOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.VPNGateway, *svcsdk.DeleteVpnGatewayInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.VPNGateway, _ *svcsdk.DeleteVpnGatewayOutput, err error) error {
	return err
}
func nopUpdate(context.Context, cpresource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
